name: CI/CD - Tic Tac Toe React

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Correr tests (Vitest)
        run: npm run test -- --run

      - name: Build de la app
        run: npm run build

  cd:
    name: Deploy en Render
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Llamar al Deploy Hook de Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"